// ── Cratua Media Forge — Frontend ──
import { invoke } from '@tauri-apps/api/core';
import { open as dialogOpen, confirm } from '@tauri-apps/plugin-dialog';
import { listen } from '@tauri-apps/api/event';
import { getCurrentWebview } from '@tauri-apps/api/webview';

// ── State ──
const S = { mode:'simple', presets:[], selectedPreset:'web-h264', params:{ video_codec:'H264',width:1920,height:1080,scale_algorithm:'Lanczos',fps:'SameAsSource',crf:19,video_bitrate:null,max_bitrate:null,bufsize:null,preset:'Medium',profile:null,pixel_format:'Yuv420p',deinterlace:null,video_filters:[],audio_codec:'Aac',audio_bitrate:128,audio_channels:2,sample_rate:44100,audio_filters:[],container:'Mp4',movflags:['FastStart'],threads:0,metadata:{},trim_start:null,trim_end:null,extra_args:[] }, files:[], outputDir:'', jobs:[], isEncoding:false, config:null, history:[] };

const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),on=(el,ev,fn)=>el.addEventListener(ev,fn);
function normPath(p){return(p||'').replace(/\\/g,'/')}
function parseVideoFilter(s){if(s==='HFlip')return{HFlip:null};if(s==='VFlip')return{VFlip:null};if(s==='Denoise')return{Denoise:null};if(s==='Grayscale')return{Grayscale:null};const m=s.match(/^Rotate\((\d+)\)$/);return m?{Rotate:parseInt(m[1])}:{HFlip:null}}
function parseAudioFilter(s){if(s==='Loudnorm')return{Loudnorm:null};const m=s.match(/^Volume\(([0-9.]+)\)$/);return m?{Volume:parseFloat(m[1])}:{Loudnorm:null}}

// ── Diagnostic bar ──
const diagEl=document.createElement('div');diagEl.style.cssText='position:fixed;bottom:0;left:0;right:0;background:#111;color:#0f0;font:10px monospace;padding:4px 10px;z-index:999;opacity:0.9';document.body.appendChild(diagEl);
function diag(m){diagEl.textContent=m;console.log(m)}

// ── Splash ──
setTimeout(()=>{const s=$('#splash');s.style.opacity='0';s.style.transition='opacity 0.5s';setTimeout(()=>{s.classList.add('hidden');$('#app').classList.remove('hidden')},500)},2000);

// ── Mode ──
function setMode(m){S.mode=m;$('#btn-simple').className=m==='simple'?'px-3 py-1.5 text-xs font-medium rounded-md bg-rose text-white':'px-3 py-1.5 text-xs font-medium rounded-md text-[#9090a0] hover:text-white hover:bg-[#1f1f2e]';$('#btn-advanced').className=m==='advanced'?'px-3 py-1.5 text-xs font-medium rounded-md bg-rose text-white':'px-3 py-1.5 text-xs font-medium rounded-md text-[#9090a0] hover:text-white hover:bg-[#1f1f2e]';$('#mode-simple').classList.toggle('hidden',m!=='simple');$('#mode-advanced').classList.toggle('hidden',m!=='advanced')}
on($('#btn-simple'),'click',()=>setMode('simple'));on($('#btn-advanced'),'click',()=>setMode('advanced'));

// ── Tabs ──
$$('.tab-btn').forEach(b=>on(b,'click',()=>{$$('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-panel').forEach(x=>x.classList.add('hidden'));$(`#tab-${b.dataset.tab}`).classList.remove('hidden')}));
$$('.collapsible-header').forEach(h=>on(h,'click',()=>{h.classList.toggle('open');const b=h.nextElementSibling;b.style.display=b.style.display==='none'?'':'none'}));

// ── FPS ──
on($('#a-fps-mode'),'change',e=>{$('#a-fps-val').classList.toggle('hidden',e.target.value!=='fixed')});

// ── Sliders ──
function bindSN(rid,nid,vid,suf){const r=$(rid),n=$(nid),v=vid?$(vid):null;if(!r||!n)return;on(r,'input',()=>{n.value=r.value;if(v)v.textContent=suf?r.value+suf:r.value});on(n,'change',()=>{let x=parseInt(n.value);if(isNaN(x))return;x=Math.max(parseInt(r.min),Math.min(parseInt(r.max),x));r.value=x;n.value=x;if(v)v.textContent=suf?x+suf:x})}
bindSN('#s-crf','#s-crf-num','#s-crf-val','');bindSN('#s-audio','#s-audio-num','#s-audio-val',' kbps');
bindSN('#a-crf','#a-crf-num','#a-crf-val','');bindSN('#a-abitrate','#a-abitrate-num','#a-abitrate-val',' kbps');
on($('#a-crf-auto'),'click',()=>{$('#a-crf').value=23;$('#a-crf-num').value=23;$('#a-crf-val').textContent='23'});

// ── Filters ──
function renderFilters(){const vl=$('#vfilters-list');vl.innerHTML=S.params.video_filters.map((f,i)=>{const lb=typeof f==='string'?f:(f.HFlip?'Flip H':f.VFlip?'Flip V':f.Denoise?'Denoise':f.Grayscale?'Grayscale':f.Rotate?`Rotate ${f.Rotate}°`:JSON.stringify(f));return`<div class="flex items-center justify-between text-xs py-1 px-2 rounded hover:bg-[#1f1f2e]"><span class="text-[#c0c0d0]">${lb}</span><button data-vfidx="${i}" class="text-[#606070] hover:text-[#ef4444]">✕</button></div>`}).join('');vl.querySelectorAll('button').forEach(b=>on(b,'click',()=>{S.params.video_filters.splice(parseInt(b.dataset.vfidx),1);renderFilters()}));const al=$('#afilters-list');al.innerHTML=S.params.audio_filters.map((f,i)=>{const lb=typeof f==='string'?f:(f.Loudnorm?'Loudnorm':f.Volume?`Vol ${f.Volume}x`:JSON.stringify(f));return`<div class="flex items-center justify-between text-xs py-1 px-2 rounded hover:bg-[#1f1f2e]"><span class="text-[#c0c0d0]">${lb}</span><button data-afidx="${i}" class="text-[#606070] hover:text-[#ef4444]">✕</button></div>`}).join('');al.querySelectorAll('button').forEach(b=>on(b,'click',()=>{S.params.audio_filters.splice(parseInt(b.dataset.afidx),1);renderFilters()}))}
on($('#vfilter-add'),'change',e=>{if(e.target.value){S.params.video_filters.push(parseVideoFilter(e.target.value));renderFilters();e.target.value=''}});
on($('#afilter-add'),'change',e=>{if(e.target.value){S.params.audio_filters.push(parseAudioFilter(e.target.value));renderFilters();e.target.value=''}});

// ── Metadata ──
function renderMetadata(){const l=$('#metadata-list');l.innerHTML=Object.entries(S.params.metadata).map(([k,v])=>`<div class="flex items-center justify-between py-1 px-2 rounded hover:bg-[#1f1f2e]"><span class="text-[#c0c0d0]">${k}: ${v}</span><button data-mkey="${k}" class="text-[#606070] hover:text-[#ef4444]">✕</button></div>`).join('');l.querySelectorAll('button').forEach(b=>on(b,'click',()=>{delete S.params.metadata[b.dataset.mkey];renderMetadata()}))}
on($('#meta-add'),'click',()=>{const k=$('#meta-key').value.trim(),v=$('#meta-val').value.trim();if(k){S.params.metadata[k]=v;renderMetadata();$('#meta-key').value='';$('#meta-val').value=''}});

// ── Files ──
function addFiles(paths){diag('addFiles: '+(paths?paths.length:0)+' paths');if(!paths||!paths.length)return;const np=paths.map(normPath).filter(p=>!S.files.includes(p));if(np.length)S.files.push(...np);renderFiles();updateStatus();diag('Files: '+S.files.length)}
function renderFiles(){const l=$('#file-list');if(!S.files.length){l.innerHTML='<div class="text-[#606070] text-xs p-2 text-center">Drop files or click + Add Files</div>'}else{l.innerHTML=S.files.map((f,i)=>`<div class="flex items-center justify-between text-xs py-1 px-2 rounded hover:bg-[#1f1f2e]"><span class="truncate text-[#c0c0d0]" title="${f}">${f.split('/').pop()}</span><button data-fidx="${i}" class="text-[#606070] hover:text-[#ef4444]">✕</button></div>`).join('');l.querySelectorAll('button').forEach(b=>on(b,'click',()=>{S.files.splice(parseInt(b.dataset.fidx),1);renderFiles();updateStatus()}))}}
on($('#btn-add-files'),'click',async()=>{diag('Add Files clicked');try{const sel=await dialogOpen({multiple:true,filters:[{name:'Media',extensions:['mp4','mkv','mov','avi','webm','mp3','wav','flac','m4a','ogg']}]});if(sel){addFiles(Array.isArray(sel)?sel:[sel]);diag('Dialog returned '+sel.length+' files')}else{diag('Dialog cancelled')}}catch(e){diag('Dialog error: '+e)}});
on($('#btn-browse'),'click',async()=>{diag('Browse clicked');try{const sel=await dialogOpen({directory:true,multiple:false,title:'Select Output Folder'});if(sel){S.outputDir=normPath(typeof sel==='string'?sel:sel[0]);$('#output-dir').textContent=S.outputDir;if(S.config){S.config.output_dir=S.outputDir;invoke('save_config',{config:S.config}).catch(()=>{})}diag('Output: '+S.outputDir)}}catch(e){diag('Browse error: '+e)}});
on($('#path-input'),'keydown',e=>{if(e.key==='Enter'){addFiles([e.target.value.trim()]);e.target.value=''}});
on($('#btn-clear-files'),'click',()=>{S.files=[];renderFiles();updateStatus()});

// ── Drag-drop ──
async function setupDragDrop(){try{const wv=getCurrentWebview();await wv.onDragDropEvent(ev=>{if(ev.payload.type==='over')$('#file-list').classList.add('ring-2','ring-rose');else if(ev.payload.type==='leave')$('#file-list').classList.remove('ring-2','ring-rose');else if(ev.payload.type==='drop'){$('#file-list').classList.remove('ring-2','ring-rose');if(ev.payload.paths?.length){addFiles(ev.payload.paths);diag('Dropped: '+ev.payload.paths.length+' files')}}})}catch(e){diag('Drag-drop error: '+e)}}

function updateStatus(){$('#status-count').textContent=`${S.files.length} files | ${S.jobs.length} jobs`}

// ── Params ──
function collectSimpleParams(){return{...S.params,width:parseInt($('#s-width').value)||1920,height:parseInt($('#s-height').value)||1080,crf:parseInt($('#s-crf').value)||19,audio_bitrate:parseInt($('#s-audio').value)||128,deinterlace:$('#s-deint').checked?'Yadif':null}}
function collectAdvParams(){const fps=$('#a-fps-mode').value==='fixed'?{Fixed:parseInt($('#a-fps-val').value)||30}:'SameAsSource';const sm={ultrafast:'Ultrafast',superfast:'Superfast',veryfast:'Veryfast',faster:'Faster',fast:'Fast',medium:'Medium',slow:'Slow',slower:'Slower',veryslow:'Veryslow'};const pm={yuv420p:'Yuv420p',yuv422p:'Yuv422p',yuv444p:'Yuv444p',nv12:'Nv12',rgb24:'Rgb24'};const mf=[];if($('#a-faststart').checked)mf.push('FastStart');if($('#a-fragkf').checked)mf.push('FragKeyframe');const ea=$('#a-extra-args').value.trim();return{...S.params,video_codec:$('#a-vcodec').value||'H264',audio_codec:$('#a-acodec').value||'Aac',container:$('#a-container').value||'Mp4',crf:parseInt($('#a-crf').value)??null,video_bitrate:parseInt($('#a-vbitrate').value)||null,max_bitrate:parseInt($('#a-maxbr').value)||null,bufsize:parseInt($('#a-bufsize').value)||null,preset:sm[$('#a-preset-speed').value||'medium']||'Medium',profile:$('#a-profile').value?$('#a-profile').value.charAt(0).toUpperCase()+$('#a-profile').value.slice(1):null,pixel_format:pm[$('#a-pixfmt').value||'yuv420p']||'Yuv420p',deinterlace:$('#a-deint').checked?($('#a-deint-method').value==='bwdif'?'Bwdif':'Yadif'):null,fps,width:parseInt($('#a-width').value)||1920,height:parseInt($('#a-height').value)||1080,scale_algorithm:$('#a-scale').value||'Lanczos',audio_bitrate:parseInt($('#a-abitrate').value)||128,audio_channels:parseInt($('#a-channels').value)||2,sample_rate:parseInt($('#a-samplerate').value)||44100,threads:parseInt($('#a-threads').value)||0,movflags:mf,trim_start:$('#a-trim-start').value.trim()||null,trim_end:$('#a-trim-end').value.trim()||null,extra_args:ea?ea.split(/\s+/).filter(Boolean):[]}}

// ── Preset selector ──
on($('#preset-select'),'change',()=>{const id=$('#preset-select').value,p=S.presets.find(x=>x.id===id);if(p&&p.params){S.selectedPreset=id;S.params={...p.params};['s','a'].forEach(pre=>{const crf=$(pre==='s'?'#s-crf':'#a-crf'),crfn=$(pre==='s'?'#s-crf-num':'#a-crf-num'),crfv=$(pre==='s'?'#s-crf-val':'#a-crf-val');if(crf){crf.value=p.params.crf??19;if(crfn)crfn.value=p.params.crf??19;if(crfv)crfv.textContent=p.params.crf??19}const w=$(pre==='s'?'#s-width':'#a-width'),h=$(pre==='s'?'#s-height':'#a-height');if(w)w.value=p.params.width||1920;if(h)h.value=p.params.height||1080;const ab=$(pre==='s'?'#s-audio':'#a-abitrate'),abn=$(pre==='s'?'#s-audio-num':'#a-abitrate-num'),abv=$(pre==='s'?'#s-audio-val':'#a-abitrate-val');if(ab){ab.value=p.params.audio_bitrate||128;if(abn)abn.value=p.params.audio_bitrate||128;if(abv)abv.textContent=(p.params.audio_bitrate||128)+' kbps'}const di=$(pre==='s'?'#s-deint':'#a-deint');if(di)di.checked=!!p.params.deinterlace});renderFilters();renderMetadata()}});

// ── Save preset ──
on($('#btn-save-preset'),'click',async()=>{const name=prompt('Preset name:');if(!name)return;const params=S.mode==='simple'?collectSimpleParams():collectAdvParams();const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const exists=S.presets.find(p=>p.id===id);if(exists){if(!await confirm(`Preset "${exists.name}" already exists. Overwrite?`))return}try{await invoke('create_preset',{preset:{id,name,description:'Custom preset',category:'Video',params}});S.presets=await invoke('get_presets');const sel=$('#preset-select');sel.innerHTML=S.presets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');sel.value=id;diag('Preset saved: '+name)}catch(e){diag('Save preset error: '+e)}});

// ── Delete preset ──
on($('#btn-delete-preset'),'click',async()=>{const id=$('#preset-select').value;const p=S.presets.find(x=>x.id===id);if(!p)return;const builtin=['default','web-h264','web-h265','web-vp9','archive-h264','audio-mp3','audio-aac','audio-opus','gif'];if(builtin.includes(id)){diag('Cannot delete built-in preset');return}if(!await confirm(`Delete preset "${p.name}"?`))return;try{await invoke('delete_preset',{id});S.presets=await invoke('get_presets');const sel=$('#preset-select');sel.innerHTML=S.presets.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');diag('Preset deleted')}catch(e){diag('Delete preset error: '+e)}});

// ── Queue ──
on($('#btn-add-queue'),'click',()=>{if(!S.files.length){diag('No files');return}const bp=S.mode==='simple'?collectSimpleParams():collectAdvParams();const ext=bp.container.toLowerCase();const ow=[];S.files.forEach(f=>{const nm=f.split('/').pop(),st=nm.includes('.')?nm.substring(0,nm.lastIndexOf('.')):nm;let out=`${S.outputDir}/${st}.${ext}`;if(out===f){out=`${S.outputDir}/${st}_converted.${ext}`;ow.push(nm)}S.jobs.push({input:f,output:out,params:structuredClone(bp),status:'pending',progress:0})});S.files=[];renderFiles();renderQueue();if(ow.length){$('#status-text').textContent=`Renamed ${ow.length} to _converted`;$('#status-text').classList.add('text-[#f59e0b]');setTimeout(()=>$('#status-text').classList.remove('text-[#f59e0b]'),5000)}else{$('#status-text').textContent=`Queued ${S.jobs.length} job(s)`}diag('Queued: '+S.jobs.length+' jobs')});
function renderQueue(){const l=$('#queue-list');if(!S.jobs.length){l.innerHTML='';updateStatus();return}l.innerHTML=S.jobs.map(j=>{const inn=j.input.split('/').pop(),outn=j.output.split('/').pop();switch(j.status){case'pending':return`<div class="flex items-center justify-between text-xs py-1 px-2"><span class="text-[#c0c0d0] truncate">${inn} → ${outn}</span><span class="text-[#606070] shrink-0 ml-2">pending</span></div>`;case'running':return`<div class="text-xs py-1"><div class="flex justify-between text-[#c0c0d0] mb-1"><span class="truncate">${inn}</span><span>${Math.round(j.progress)}%</span></div><div class="progress-bar"><div class="progress-bar-fill" style="width:${Math.max(1,j.progress)}%"></div></div></div>`;case'done':return`<div class="flex items-center justify-between text-xs py-1 px-2"><span class="text-[#22c55e] truncate">✓ ${inn} → ${outn}</span><span class="text-[#22c55e] shrink-0 ml-2">done</span></div>`;case'failed':return`<div class="flex flex-col text-xs py-1 px-2"><div class="flex items-center justify-between"><span class="text-[#ef4444] truncate">✗ ${inn}</span><span class="text-[#ef4444] shrink-0 ml-2">failed</span></div><div class="text-[#606070] mt-1 text-[10px] truncate" title="${j.error||''}">${j.error||'unknown'}</div></div>`;case'cancelled':return`<div class="flex items-center justify-between text-xs py-1 px-2"><span class="text-[#f59e0b] truncate">⊘ ${inn}</span><span class="text-[#f59e0b] shrink-0 ml-2">cancelled</span></div>`;default:return''}}).join('');updateStatus()}

// ── Re-queue + Clear Queue ──
on($('#btn-requeue'),'click',()=>{const done=S.jobs.filter(j=>j.status==='done'||j.status==='failed'||j.status==='cancelled');if(!done.length){diag('No finished jobs to re-run');return}const files=done.map(j=>j.input);S.jobs=S.jobs.filter(j=>j.status==='pending'||j.status==='running');addFiles(files);renderQueue();diag('Re-run: '+files.length+' file(s) back to list')});
on($('#btn-clear-queue'),'click',()=>{const before=S.jobs.length;S.jobs=S.jobs.filter(j=>j.status==='pending'||j.status==='running');renderQueue();diag('Cleared '+(before-S.jobs.length)+' finished job(s)')});

// ── Encoding ──
on($('#btn-start'),'click',async()=>{if(!S.jobs.length||S.isEncoding)return;const pend=S.jobs.filter(j=>j.status==='pending');if(!pend.length)return;diag('Checking overwrites...');const outs=pend.map(j=>j.output);try{const ex=await invoke('check_output_overwrite',{paths:outs});if(ex.length){if(!await confirm(`${ex.length} output file(s) already exist:\n${ex.map(p=>p.split('/').pop()).join(', ')}\n\nOverwrite?`)){diag('Cancelled: files exist');$('#status-text').textContent='Cancelled — files exist';return}}}catch(e){}S.isEncoding=true;$('#btn-start').disabled=true;$('#btn-cancel').classList.remove('hidden');$('#status-text').textContent='Encoding...';const jd=pend.map(j=>({input_path:j.input,output_path:j.output,params:j.params}));diag('Starting '+jd.length+' job(s)...');try{await invoke('start_encoding',{jobData:jd,ffmpegPath:S.config?.ffmpeg_path||null})}catch(e){diag('ERROR: '+String(e).substring(0,100));$('#status-text').textContent=String(e);pend.forEach(j=>{j.status='failed';j.error=String(e)});renderQueue();finishEncoding()}});
function finishEncoding(){S.isEncoding=false;$('#btn-start').disabled=false;$('#btn-cancel').classList.add('hidden')}
on($('#btn-cancel'),'click',async()=>{await invoke('cancel_encoding');S.jobs.forEach(j=>{if(j.status==='pending'||j.status==='running')j.status='cancelled'});renderQueue();finishEncoding();$('#status-text').textContent='Cancelled';diag('Cancelled')});

// ── Events ──
async function setupEvents(){await listen('job:progress',e=>{const d=e.payload,j=S.jobs.find(x=>x.status==='running'||x.status==='pending');if(j){j.status='running';j.progress=d.progress_pct??0}renderQueue()});await listen('job:done',e=>{const d=e.payload,j=S.jobs.find(x=>x.status==='running');if(j){j.status=d.status==='completed'?'done':(d.status==='cancelled'?'cancelled':'failed');j.error=d.error;j.command=d.command||''}renderQueue();if(S.jobs.every(x=>x.status==='done'||x.status==='failed'||x.status==='cancelled')){finishEncoding();loadHistory();if(S.jobs.some(x=>x.status==='done')){const cmd=S.jobs.find(x=>x.command)?.command||'';$('#status-text').textContent='Complete'+(cmd?' — '+cmd.split(' ').slice(0,6).join(' ')+'...':'')}diag('All jobs done')}})}

// ── Modals ──
on($('#btn-settings'),'click',()=>$('#settings-modal').classList.remove('hidden'));on($('#btn-settings-cancel'),'click',()=>$('#settings-modal').classList.add('hidden'));on($('#btn-settings-save'),'click',async()=>{if(S.config)S.config.ffmpeg_path=$('#ffmpeg-path').value||null;await invoke('save_config',{config:S.config});$('#settings-modal').classList.add('hidden')});
on($('#btn-about'),'click',()=>$('#about-modal').classList.remove('hidden'));on($('#btn-about-close'),'click',()=>$('#about-modal').classList.add('hidden'));

// ── History ──
async function loadHistory(){try{S.history=await invoke('get_history');renderHistory()}catch(e){diag('History error: '+e)}}
function renderHistory(){const l=$('#history-list');if(!l)return;if(!S.history.length){l.innerHTML='<div class="text-[#606070] text-xs p-2">No jobs yet</div>';return}l.innerHTML=S.history.slice(-20).reverse().map(h=>{const inn=h.input_path.split('/').pop()||h.input_path,outn=h.output_path.split('/').pop()||h.output_path,date=new Date(h.created_at*1000).toLocaleString(),dur=h.duration_secs?`(${h.duration_secs.toFixed(1)}s)`:'',ok=h.status==='completed',icon=ok?'✓':h.status==='cancelled'?'⊘':'✗',color=ok?'text-[#22c55e]':h.status==='cancelled'?'text-[#f59e0b]':'text-[#ef4444]';return`<div class="flex items-center gap-2 text-xs py-1 px-2 rounded hover:bg-[#1f1f2e]"><span class="${color} w-4">${icon}</span><span class="text-[#c0c0d0] truncate flex-1" title="${h.input_path}">${inn} → ${outn}</span><span class="text-[#606070] shrink-0">${dur}</span></div>`}).join('')}
on($('#btn-clear-history'),'click',async()=>{await invoke('clear_history');S.history=[];renderHistory()});

// ── Init ──
async function init(){diag('Init...');const d=[];d.push('TI:'+(!!window.__TAURI_INTERNALS__));d.push('TC:'+(!!window.__TAURI__?.core));d.push('inv:'+(typeof invoke));d.push('dia:'+(typeof dialogOpen));d.push('lis:'+(typeof listen));try{S.presets=await invoke('get_presets');d.push('pre:'+S.presets.length);S.config=await invoke('get_config');S.outputDir=S.config?.output_dir||await invoke('get_default_output_dir');$('#output-dir').textContent=S.outputDir;await setupEvents();d.push('evt:OK');await setupDragDrop();d.push('drg:OK');await loadHistory();d.push('his:OK');$('#status-text').textContent='Ready';d.push('READY')}catch(e){d.push('ERR:'+String(e).substring(0,60));S.outputDir='output';$('#output-dir').textContent=S.outputDir}diag(d.join(' | '));const sel=$('#preset-select');sel.innerHTML=S.presets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');renderFilters();renderMetadata();renderFiles()}
init();
